version: '3.8'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - grafana_network

  database:
    image: postgres:alpine
    networks:
      - grafana_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mqtt_database
    volumes:
      - /home/toby/git/docker-compose-projects/grafana/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  mosquitto:
    image: eclipse-mosquitto
    networks:
      - grafana_network
    ports:
      - 1884:1883

  nodejs:
    image: node:14-slim
    networks:
      - grafana_network
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: /home/toby/git/docker-compose-projects/grafana/mqtt-to-timescaledb
        target: /home/node/app
    command: "npm start"
    environment:
      - PGHOST=database
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=mqtt_database
      - PGPORT=5432

networks:
  grafana_network:

